### ISSUE TITLE
error

### ISSUE THREAD

**Issue by shedman214** [majora2007/plex-anime-tags#10]
i keep getting this same error any help on what it means

![image](https://user-images.githubusercontent.com/32603273/116963362-404b7880-ac6e-11eb-9ec1-ebce071fc193.png)

**Comment by majora2007** [comment]
From the stack trace, this looks like pyMongo isn't able to connect to your local Mongo connection. Can you confirm you have MongoDB installed and running on your PC while you run this (it is needed to cache the data else you get banned pretty fast from these metadata providers).

**Comment by shedman214** [comment]
Where do I get a Mongo connection at?

**Comment by majora2007** [comment]
1. You need to download and install the database. It is lightweight and runs in memory. You can get it [here](https://www.mongodb.com/try/download/community)
2. In your settings.ini file, where you configure your AniDB token and Plex connection, you can change the mongodb connection string. If you don't customize the install, then you can leave it as is.

Try that out and let me know.

**Comment by shedman214** [comment]
i installed it and still didnt work 
![image](https://user-images.githubusercontent.com/32603273/117020615-38b2c080-acbc-11eb-83dd-e5f04ed84660.png)
![image](https://user-images.githubusercontent.com/32603273/117020677-49633680-acbc-11eb-9742-1d43c394123d.png)

**Comment by shedman214** [comment]
for cache_mongodb i have my IP:27017

**Comment by majora2007** [comment]
I haven't tested this in docker, but it should work. What version of python are you running and can you verify you did the pip install -r requirements.txt to install all dependencies?

**Comment by shedman214** [comment]
![image](https://user-images.githubusercontent.com/32603273/117025997-00fa4780-acc1-11eb-9a85-aacd856fdb24.png)

**Comment by shedman214** [comment]
python 3

**Comment by majora2007** [comment]
Can you try: pip install lxml? It looks like the xml parser out of the box is missing (or I forgot to include a dependency).

**Comment by shedman214** [comment]
could it be my plex blocking it: 
![image](https://user-images.githubusercontent.com/32603273/117028840-b29a7800-acc3-11eb-9da5-6ba69908f192.png)

**Comment by majora2007** [comment]
Yeah, I think that might be the issue. I just ran the script on my local and it worked. Did you set the token for your plex instance and your Anime library name?

**Comment by shedman214** [comment]
i think i got it to work 
![image](https://user-images.githubusercontent.com/32603273/117032865-79640700-acc7-11eb-8d85-4b22446774b5.png)

**Comment by majora2007** [comment]
Close, the client version is missing, meaning you're not getting data back from AniDB. Try either clientver of 1 or 2 unless you're using your own client and not mine.

**Comment by shedman214** [comment]
![image](https://user-images.githubusercontent.com/32603273/117035187-a31e2d80-acc9-11eb-989c-67129a3eca36.png)

**Comment by shedman214** [comment]
it might be my client. where do i get my client on anidb. i didn't understand that part either
is that my user name

**Comment by majora2007** [comment]
Ahh you changed it from mine. Client is something you can create yourself on AniDB (it is not required tho). 

https://anidb.net/perl-bin/animedb.pl?show=client

I would honestly just use the one I ship with.

**Comment by shedman214** [comment]
this is your so just leave client like it is???
![image](https://user-images.githubusercontent.com/32603273/117061800-3b2b0f80-ace8-11eb-96f4-23e2f0c957e8.png)

**Comment by shedman214** [comment]
![image](https://user-images.githubusercontent.com/32603273/117062082-9f4dd380-ace8-11eb-869a-40202d3db6df.png)

**Comment by majora2007** [comment]
Oh, lol. Sorry, I guess you do need to register your own. Sorry, it's been some time since I worked on this. 

Yeah you can create your own like in your picture, or you can just try mine. I don't think this app will get enough hits for it to matter plus I use caching.

plexanimetags
clientver=2

**Comment by shedman214** [comment]
![image](https://user-images.githubusercontent.com/32603273/117063145-0ae47080-acea-11eb-907c-216fe29a1c0f.png)

![image](https://user-images.githubusercontent.com/32603273/117063171-120b7e80-acea-11eb-8226-9186b845dafc.png)

**Comment by majora2007** [comment]
That error is with hitting your plex server. The script is unable to connect with it.

**Comment by shedman214** [comment]
when i put it on clinetverse=1 i get this? 
![image](https://user-images.githubusercontent.com/32603273/117064949-6f083400-acec-11eb-8fdf-55d3a4adc1af.png)

**Comment by majora2007** [comment]
Yeah...it's working now.

**Comment by shedman214** [comment]
thank you for your help

**Comment by majora2007** [comment]
You're welcome. Enjoy!

**Comment by shedman214** [comment]
simple question once it is done for the first round of adding genres will it only update the most recently added shows after that?

**Comment by majora2007** [comment]
Not exactly. 

What happens is if the cache has expired, we refresh from the metadata provider. If there are differences in tags, then it will write the new ones over. If will never overwrite locked tags. 

Each series is still checked, but because you have mongodb, it's insanely fast to check against the cache, so in reality, only new series will get genres.

**Comment by shedman214** [comment]
what does it mean by parser library? 
![image](https://user-images.githubusercontent.com/32603273/118401315-d9916c00-b62a-11eb-8bfc-7106d4c7acbf.png)

**Comment by majora2007** [comment]
I thought we fixed this earlier. Parser comes from the library beautiful soup 4 which is responsible for reading the data of the metadata.

It's saying the xml parser is missing from beautiful soup 4. Pip install lxml is what I told you earlier to run, can you try again and see if it changes anything?
